### ISSUE TITLE
Editor screen is shrunken and off to the left side of the viewport.

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#108]
Might have been introduced around cc562c0e0cf6e5a608882d89ca9aac9e2df5dc52, not sure.  Definitely a recent regression.

![image](https://cloud.githubusercontent.com/assets/863312/10215308/f10c44ac-67e5-11e5-96eb-b7b561600fc1.png)

**Comment by davewx7** [comment]
Have you tried a full rebuild? I don't reproduce this.

**Comment by DDR0** [comment]
Repro case: Start ./anura --level=to-nenes-house.cfg, press ctrl-e, get stretched screen.
Non-repro case: Start ./anura --level=to-nenes-house.cfg --edit, get the normal screen.

**Comment by rkettering** [comment]
I did a full clean build, and I'm still seeing exactly what DDR is.  Note also that if you start with --edit, upon exiting the editor, the regular game visuals are now stretched, horizontally.

**Comment by rkettering** [comment]
Fixed in duplicate issue #119.
