### ISSUE TITLE
levels with the darkness overlay have a spectacular (1GB / 3sec) memory leak

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#115]
Can reproduce on:
--level crevice-village-house-2-basement-backroom.cfg
--level dungeon-entrance.cfg

Cannot reproduce on (the following levels don't have the darkness overlay):
--level grassy-path.cfg
--level foreboding-forest.cfg
--level dungeon-blocks.cfg

**Comment by KroArtem** [comment]
I'm not sure what are you speaking exactly, but when I enter Nena's basement where ants should be destroyed, the game hangs and since I have no swap everything completely freezes.

**Comment by rkettering** [comment]
Yep - that's definitely such a level.  It has the darkness overlay on it to make it look like the lights are actually "casting light" in some sense.

**Comment by rkettering** [comment]
Fixed by 5e32a94d00fb
