### ISSUE TITLE
Editor views have the visible part of the level squished by 50% horizontally

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#119]
![image](https://cloud.githubusercontent.com/assets/863312/12070416/8103ed62-b039-11e5-85db-d915cb20b12d.png)

**Comment by rkettering** [comment]
The specific commit that introduced this issue was https://github.com/anura-engine/anura/commit/6ce921224f7bb8ab18ade1b7654ad479c9f83b49

**Note that this does not reproduce on all levels, or even most levels**.  Quite a few levels will not reproduce this problem (I can't tell if their editor dimensions are absolutely correct, or if they're just "close enough" to look okay at a glance.  Examples of levels that don't reproduce this problem would be `milgrams-basement-junction.cfg` and `tempo-village.cfg`.  This may be why this fairly old issue lay dormant for a while - I think we got fooled by it seeming to have gone away when I switched focus from one area of the game to another - by editing the wrong levels, I may have been blind to the problem still being present.

The primary example of a level that **does** exhibit the problem is: `to-nenes-house.cfg`.

**Comment by sweetkristas** [comment]
I bet it's any level that uses level frame buffers.

**Comment by rkettering** [comment]
I'm not sure what that means..  could you describe it, briefly?

I notice that it's not reproducing on `chopple-shop.cfg` - a distinguishing feature of that level, compared to `to-nenes-house.cfg`, is that chopple-shop does not have water.

**Comment by sweetkristas** [comment]
Levels with water use level based frame buffers to do the water moving
using a shader.

**Comment by rkettering** [comment]
Thank you - that makes sense. :thumbsup:
