### ISSUE TITLE
Failing to launch any build

### ISSUE THREAD

**Issue by ghost** [anura-engine/anura#124]
Some of you might know about this from IRC. I can't figure out what's going.
I'm on Win 10 pro X64. I've built both 32-64bits binaries, release and releaseXP.
Followed the build instructions from the wiki as well, downloaded Anura's pre-builts.
For some strange reason all the binaries just opens quickly and closes.
It closes so fast that I can't even a crash dump report.

**Comment by sweetkristas** [comment]
Do you have any modules in the module/ folder?

There should be a stderr.txt file in the same directory as the Anura.exe
binary.

**Comment by ghost** [comment]
Haha, I just saw the thing about modules in the command prompt and started telling Jetrel about it. It's my fault for not reading the documentation properly. We can consider this closed.
