### ISSUE TITLE
background palettes are getting stuck upon moving between associated levels

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#125]
##### Repro case 1:
- start the game on `forest-crossroads.cfg`
  - the game will have the bright-green `forest_verdant` palette, both on the foreground, and background
- move right/east onto the level `twisted-trees.cfg`
  - the game has the blue `forest_clean` palette, both on the foreground and background
- return west to the level `forest-crossroads.cfg`.
  - the game now has the bright-green `forest_verdant` palette for the foreground, **but incorrectly still has the blue `forest_clean` palette applied to the background.**
##### Repro case 2:
- start the game on `tempo-bridge.cfg`
  - the game will have the bright-green `forest_verdant` palette, both on the foreground, and background
- move right/east onto the level `sweltering-swamp.cfg`
  - the game has the much darker `forest_decay` palette, both on the foreground and background
- return west to the level `tempo-bridge.cfg`.
  - the game now has the bright-green `forest_verdant` palette for the foreground, **but incorrectly still has the `forest_decay` palette applied to the background.**

**Comment by davewx7** [comment]
Fixed.
