### ISSUE TITLE
HUD objects need to have a way to be exempt from level darkness.

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#128]
Since we're now doing HUD elements via objects, this is one regression against the specialized HUD objects of the past.

Making darkness configurable, to be applied only to certain ranges of zorders, would be the perfect solution.

Ideally, darkness could be applied by an object, which would set level variables describing the state of the darkness, allowing us to alter the overall level darkness based on game state.  Uses of this include:
- marking regions in which darkness will suddenly take effect, or go away
- allowing a common zelda-style puzzle, where the player managing to light enough light sources doesn't merely create local lights around those sources, but actually raises the apparent "ambient light level" of the entire level, illuminating everything (temporarily).
- allowing enemies or hazards that blind the player somehow (say, an octopus enemy that sprays ink at the player), or fog that does something similar (nevertheless allowing them to make out major light sources to at least estimate their position, even if they can see what's immediately around them).

**Comment by DDR0** [comment]
This was fixed when we moved away from engine darkness to our current ffl-based system.
