### ISSUE TITLE
Better error message on formula.cpp:1245 - output not just the desired type, but also the offending type

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#130]
It'd be very helpful not just to declare what type we expected something to be, but to declare in addition, what type it actually ended up being - it's clear something went wrong, but that would give us a lot more evidence as to **where** it went wrong.

```
CRITICAL: formula.cpp:1245 ASSERTION FAILED: FUNCTION CALL DOES NOT MATCH: At modules/frogatto/data/objects/effects/experimental/hp_bar_attache.cfg 28:
[ [color_as_fraction(color_as_int) | color_as_int <- combined_colors ] | co...
   ^------------------------------^
```

**Comment by davewx7** [comment]
It doesn't look like you pasted the full error message? I'm not sure what code you have and the context, but if I try a simple test of this code:

```
 set_gui_stats_alpha('hi'),
```

with the function expecting an integer I get this:

ERROR: asserts.cpp:145 : ASSERT FAIL: formula.cpp:1245 ASSERTION FAILED: FUNCTION CALL DOES NOT MATCH: At modules/citadel/data/objects/creature.cfg 59:
set_gui_stats_alpha('hi'),
^------------------------^
 ARGUMENT 1 TYPE string DOES NOT MATCH decimal

Which seems very reasonable. Maybe there is something specific about your case though which is making it not give as helpful a messag.e
