### ISSUE TITLE
The engine crashes if you hit page up or page down

### ISSUE THREAD

**Issue by Autofire** [anura-engine/anura#145]
I'm running on Windows 10 Pro. (64bit)

The engine always crashes whenever I hit page up/down in the text editor screen. This usually isn't a problem except that my laptop has page up/down right next to the arrow keys so it's easy to bump them.

I assume it's because it tries to page up/down but it cannot for some reason. Maybe something's become outdated?

**Comment by davewx7** [comment]
Fixed
