### ISSUE TITLE
strict_mode bug with fold()

### ISSUE THREAD

**Issue by Autofire** [anura-engine/anura#150]
I have this part of my code:

https://github.com/Autofire/blind/blob/1e97e763ce0ab74a9ee876417c0e46f49001f2c9/data/objects/effects/control/text/text_writer.cfg#L237

If I changed line 238 into `a + b`, I'd be told that I was attempting to do `any + any`. This seems like a bug because I do almost the exact same thing in the function that the `where` goes with.

**Comment by davewx7** [comment]
This should be fixed now. The problem was that map() on a string wasn't correctly returning a [string].
