### ISSUE TITLE
Debug console doesn't swallow mouse clicks

### ISSUE THREAD

**Issue by Autofire** [anura-engine/anura#153]
If there is an object underneath the debug console, then the object is selected **and** focus is given to the debug console. This is fine within Frogatto but frustrating in any game where you might happen to have objects in the lower left corner.

Also, if you pull the editor out enough that it overlaps with the debug console, you can potentially put focus on both.

**Comment by sweetkristas** [comment]
@davewx7 Made the debug console drag-able around the screen at some point. Does this alleviate your issue?

**Comment by rkettering** [comment]
Fixed in a9a66eceed828feedbb72646857540eb999124a8
