### ISSUE TITLE
Will not compile (error on ModelMatrixScope.cpp)

### ISSUE THREAD

**Issue by Aicaya** [anura-engine/anura#154]
Apologies for the bother, but when trying to compile the engine on Arch Linux (either with `make` or `quickmake.sh`), an error occurs when it gets to ModelMatrixScope.cpp and the whole thing fails. Here's the output:

```
Building: src/kre/ModelMatrixScope.cpp
src/kre/ModelMatrixScope.cpp: In destructor ‘KRE::ModelManager2D::~ModelManager2D()’:
src/kre/ModelMatrixScope.cpp:140:2: error: throw will always call terminate() [-Werror=terminate]

  ^
src/kre/ModelMatrixScope.cpp:140:2: note: in C++11 destructors default to noexcept
src/kre/ModelMatrixScope.cpp:140:93: error: throw will always call terminate() [-Werror=terminate]

                                                                                         ^
src/kre/ModelMatrixScope.cpp:140:93: note: in C++11 destructors default to noexcept
src/kre/ModelMatrixScope.cpp:140:124: error: throw will always call terminate() [-Werror=terminate]

                                                                                                                           ^
src/kre/ModelMatrixScope.cpp:140:124: note: in C++11 destructors default to noexcept
src/kre/ModelMatrixScope.cpp:141:87: error: throw will always call terminate() [-Werror=terminate]
   get_translation_stack().pop();
                                                                                       ^
src/kre/ModelMatrixScope.cpp:141:87: note: in C++11 destructors default to noexcept
src/kre/ModelMatrixScope.cpp:141:118: error: throw will always call terminate() [-Werror=terminate]
  get_translation_stack().pop();
                                                                                                                     ^
src/kre/ModelMatrixScope.cpp:141:118: note: in C++11 destructors default to noexcept
src/kre/ModelMatrixScope.cpp:142:81: error: throw will always call terminate() [-Werror=terminate]
  get_rotation_stack().pop();
                                                                             ^
src/kre/ModelMatrixScope.cpp:142:81: note: in C++11 destructors default to noexcept
cc1plus: all warnings being treated as errors
make: *** [Makefile:206: build/kre/ModelMatrixScope.o] Error 1
```

Don't know if it'll help (or if it's even related) but the prebuilt binary on theargentlark also fails, instead showing the message `error while loading shared libraries: libGLEW.so.1.10: cannot open shared object file: No such file or directory` (I have glew 1.13 installed on the system along with all the libraries mentioned on the INSTALL file).

Again, apologies for the bother, and especially if there's an obvious solution I'm missing.

**Comment by davewx7** [comment]
Can you try adding -Wno-terminate to your build options and see if that works?

**Comment by sweetkristas** [comment]
What is the compiler version you're using? 
The build on theargentlark is against the steam runtime, you should run it against this.

**Comment by Aicaya** [comment]
> Can you try adding -Wno-terminate to your build options and see if that works?

Added the option and this one compiled. Much later in the line, though, another error happened:

```
Building: src/entity.cpp
src/entity.cpp: In member function ‘void Entity::setControlStatus(const string&, bool)’:
src/entity.cpp:438:34: error: array subscript is above array bounds [-Werror=array-bounds]
  const std::string* k = std::find(keys, keys + controls::NUM_CONTROLS, key);
                         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/entity.cpp:439:15: error: array subscript is above array bounds [-Werror=array-bounds]
  if(k == keys + controls::NUM_CONTROLS) {
          ~~~~~^~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:206: build/entity.o] Error 1
```

> What is the compiler version you're using? 

I'm using GCC 6.1.1.

> The build on theargentlark is against the steam runtime, you should run it against this.

Noted. I'll test it out in a bit.

**Comment by AI0867** [comment]
The compiler correctly notes that the past-the-end pointer may be dereferenced if `key` is not in `keys`. Whether that can actually happen is not something I know.

**Comment by hagabaka** [comment]
Should we just remove -Werror in Makefile?

**Comment by hagabaka** [comment]
For the `terminate` errors, I fixed them by adding `noexcept(false)` to the destructors. But since destructors should not throw exceptions, would it be better to just remove those `ASSERT_LOG` calls?

**Comment by hagabaka** [comment]
@davewx7 any ideas how to fix it for both GCC6 and VC++?

**Comment by sweetkristas** [comment]
I've got a fix for it, will commit soon.

**Comment by sweetkristas** [comment]
Fixed.
