### ISSUE TITLE
Current blur effect doesn't play well with alternate blend modes

### ISSUE THREAD

**Issue by marcavis** [anura-engine/anura#157]
This example is found on the very first screen when loading the burning-stone.cfg level.
![screenshot](https://cloud.githubusercontent.com/assets/862945/18025841/312aab3e-6c0c-11e6-8f87-d4d2139c12ec.png)

**Comment by davewx7** [comment]
Resolved this by making the lights use blend mode ['src_alpha', 'one'] instead of ['src_alpha', 'dst_alpha']
