### ISSUE TITLE
Failed assertion on Render Level utility

### ISSUE THREAD

**Issue by marcavis** [anura-engine/anura#160]
When running:
./anura --utility=render_level to-nenes-house.cfg nenes.png
I get the following asserts:

CRITICAL: custom_object_type.cpp:644 ASSERTION FAILED: No definition for object ${me.type}.graphic

CRITICAL: At modules/frogatto/data/objects/playable/frogatto_playable.cfg 657:
object('ability_display', 0, 0, {x:-8,y:-8})
^

---

CRITICAL: stack trace:
CRITICAL:   ./anura : CustomObjectType::getDefinition(std::string const&)+0x119c
CRITICAL:   ./anura() [0xb1e1e7]
CRITICAL:   ./anura() [0xc4bfa2]
CRITICAL:   ./anura() [0xc6ff7f]
CRITICAL:   ./anura : game_logic::Formula::Formula(variant const&, game_logic::FunctionSymbolTable_, boost::intrusive_ptr<game_logic::FormulaCallableDefinition const>)+0x284
CRITICAL:   ./anura : game_logic::Formula::createOptionalFormula(variant const&, game_logic::FunctionSymbolTable_, boost::intrusive_ptr<game_logic::FormulaCallableDefinition const>, game_logic::Formula::FORMULA_LANGUAGE)+0x60
CRITICAL:   ./anura : CustomObjectType::CustomObjectType(std::string const&, variant, CustomObjectType const_, CustomObjectType const_)+0x58f6
CRITICAL:   ./anura : CustomObjectType::recreate(std::string const&, CustomObjectType const*)+0x3d8
CRITICAL:   ./anura : CustomObjectType::get(std::string const&)+0x1f9
CRITICAL:   ./anura : CustomObjectType::getOrDie(std::string const&)+0x18
CRITICAL:   ./anura : CustomObject::CustomObject(std::string const&, int, int, bool)+0x69
CRITICAL:   ./anura() [0xb17ead]
CRITICAL:   ./anura : game_logic::Formula::execute(game_logic::FormulaCallable const&) const+0x8d
CRITICAL:   ./anura : CustomObject::CustomObject(variant)+0x41fe
CRITICAL:   ./anura : PlayableCustomObject::PlayableCustomObject(variant)+0x33
CRITICAL:   ./anura : Entity::build(variant)+0x82
CRITICAL:   ./anura : Level::load_character(variant)+0x44
CRITICAL:   ./anura : Level::finishLoading()+0xb35
CRITICAL:   ./anura : UTILITY_render_level(std::vector<std::string, std::allocator<std::string> > const&)+0x82c
CRITICAL:   ./anura : test::run_utility(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+0x126
CRITICAL:   ./anura : main()+0x7345
CRITICAL:   /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf5
CRITICAL:   ./anura() [0x67e644]
CRITICAL: ---
INFO: asserts.cpp:74 : ATTEMPTING TO SEND CRASH REPORT...
Aborted

**Comment by davewx7** [comment]
I made it no longer assert, but now it renders just the loading screen image not the level. Have to look into our render pipeline to see what's up.

**Comment by sweetkristas** [comment]
fixed in https://github.com/anura-engine/anura/commit/7411965dd24ecf7a9a417a8c384f929f28e4c02f
