### ISSUE TITLE
only allow a single running instance of the game

### ISSUE THREAD

**Issue by acsipak** [anura-engine/anura#166]
Only allow a single running instance (per user?) of the game.

(My child occasionally clicks too many times on the desktop icon, which results in a second instance firing up, which results in some performance loss. Also the game music is weird.)

If there's a valid use case for running multiple instances, then it should be an opt-in feature which can be enabled via command line switches.

(This feature request was originally filed against the frogatto project, see https://github.com/frogatto/frogatto/issues/309 )

**Comment by rkettering** [comment]
👍

**Comment by Autofire** [comment]
I support so long as it is only one instance per *module*. There is times where I have wanted two separate modules open at once, but I have never wanted the some module open twice. (I think...)

The main reason is that I typically use Anura's builtin editor. I'm guessing that weird things would happen if you tried modifying the same module with two separate instances.

Of course, just to future-proof things, it's probably best provide a command-line option to allow the user to bypass this check.

**Comment by DDR0** [comment]
I don't know what OS you're using, but you could rely on another program to add that behaviour for now. Here's one, named `an-once.sh`, for Ubuntu Linux. (It should be run in the same folder as the anura executable.)

```
#!/bin/bash
ps cax | grep anura > /dev/null
if [ $? -eq 0 ]; then
  echo "Not launching game; game is already running."
else
  ./anura $@
fi
```

**Comment by acsipak** [comment]
@DDR0 That may be a solution for Linux / shell scripting geeks, but I guess the games based on anura have a wider intented audience than that. Average Jane won't even start to fix this problem via sh magic, instead she will uninstall the game and go visit Steam for some other game that gives her the luxury of ignorance for a fistful of dollars.

**Comment by DDR0** [comment]
Hm, yes. I retract my previous solution, it was dumb for that reason. Thank you.

**Comment by sweetkristas** [comment]
This would break anything that uses child processes, such as the turn based matchmaking server, which in turn will break Argentum Age in a bad way. It is normal for multiple instances of programs to run if you click them multiple times.

Going to close this, as further discussion seems unproductive.
