### ISSUE TITLE
imgui not downloading with trunk checkout - imgui.h missing error

### ISSUE THREAD

**Issue by macxcool** [anura-engine/anura#173]
I'm using the anura-git package from the AUR in archlinux. It just checks out the 'trunk' branch from git and does 'make'
I get:

`Building: src/kre/imgui_impl_sdl_gl3.cpp
src/kre/imgui_impl_sdl_gl3.cpp:13:19: fatal error: imgui.h: No such file or directory
 #include "imgui.h"
                   ^
compilation terminated.
make: *** [Makefile:223: build/kre/imgui_impl_sdl_gl3.o] Error 1`
I don't know too much about how to use git, but it looks like the imgui folder isn't coming down with the rest. Am I doing something wrong?

**Comment by sweetkristas** [comment]
try using 
`git submodule update --init --recursive`

**Comment by macxcool** [comment]
I get an "Permission denied (publickey)."

**Comment by sweetkristas** [comment]
I suspect you are using a DSA key. I suggest making a new 2048-bit RSA key
and loading that onto your github account and trying again.

**Comment by macxcool** [comment]
OK. Thanks for your help. This isn't a bug, so go ahead and close it. I'll work it out.
Thanks for working on Anura ;-). Frogatto is awesome.

**Comment by hagabaka** [comment]
Maybe the submodule should use `https://github.com/sweetkristas/imgui.git` rather than `git@github.com:sweetkristas/imgui.git` as the source, so that people without ssh can get it.

**Comment by ghost** [comment]
Neither combination of `git submodule update` giving anything.

Cloning `imgui` from @sweetkristas and putting it (or symlinking) where the placeholder is does the trick (for Xcode at least) and is being _easier_ if I am not doing something wrong...

**Comment by ghost** [comment]
Oh so that is what `git submodule update --init --recursive` does too (for me only when using `https://github.com/sweetkristas/imgui.git` as submodule URL as @hagabaka tells).
