### ISSUE TITLE
Changing Resolution from 1280x800 messes up Menu UI

### ISSUE THREAD

**Issue by SquishiSprite** [anura-engine/anura#183]
Menu -> Video Options -> Resolution

Any resolution other than 1280x800 makes the buttons and text appear all messy. (Smaller resolutions keeps the text above the buttons, but larger resolutions hides the text behind the buttons. Can be tricky to go back and change the resolution back!)

![frog res](https://user-images.githubusercontent.com/30911932/29194389-3d130734-7e21-11e7-8896-5319f02935b4.png)
(Example Resolution - 1024 x 768)

**Comment by ghost** [comment]
Observable by turning full screen on too, by hitting Ctrl+F.

**Comment by ghost** [comment]
I had a first look into this.

I don't know yet what is happening.

There are a couple interesting constants in [PAUSE_GAME_RESULT show_pause_game_dialog()](https://github.com/anura-engine/anura/blob/80021e4e4f823faffc71e3ac1e54284cb0619fb0/src/pause_game_dialog.cpp#L53) worth mentioning though:

https://github.com/anura-engine/anura/blob/80021e4e4f823faffc71e3ac1e54284cb0619fb0/src/pause_game_dialog.cpp#L207-L208

These get different values depending on if full screen is active (then they get `1280x800` at my laptop) or not (then they get `~960x~720`, at my laptop and when based on https://github.com/galegosimpatico/anura/commit/cfc1fd1fbab3bf1035a9c45f3aa29c9b3c836844 which is not current `trunk` but should be mostly equivalent to relatively recent `trunk`).

This is what happens at my `1280x800` laptop:

![https://frupic.frubar.net/shots/36752.png](https://frupic.frubar.net/shots/36752.png)
[https://frupic.frubar.net/36752](https://frupic.frubar.net/36752)

By hardwiring `~960x~720` in `screen_w` and `screen_h` the same picture would be like this:

![https://frupic.frubar.net/shots/36751.png](https://frupic.frubar.net/shots/36751.png)
[https://frupic.frubar.net/36751](https://frupic.frubar.net/36751)

In the first image (clean cfc1fd1fbab3) the window and buttons are in correct position.

In the second image (hard wired `show_pause_game_dialog()#screen_w` and `show_pause_game_dialog()#screen_h` values on top of cfc1fd1fbab3) window and buttons move out of place, but coincidentally the texts get to their correct positions.

**Comment by DDR0** [comment]
Offending draw call seems to be in button.cpp:243, `label_->draw(x(),y(),getRotation(),getScale());`.

**Comment by DDR0** [comment]
There seem to be some other issues around changing resolution, the text *texture* isn't getting updated appropriately either. Offset seems to work for it though.

**Comment by DDR0** [comment]
OK, so it's not the loc setting on 229 or the offset on 243 that are the problem - setting them to 0, the problem persists.

**Comment by DDR0** [comment]
It may be something going wrong in the KRE render stack upon resize, set in `ModelManager2D mm(...)` in widget.cpp:372, in the draw function there.

**Comment by DDR0** [comment]
Good news I have figured out how to rotate the level camera.
![image](https://user-images.githubusercontent.com/862627/178087215-5023b77d-3e4e-4f39-8eb1-e183e9a37f26.png)

**Comment by DDR0** [comment]
Good news. The entire main menu is now offset when doing this, so uhhhh _technically_ it's better now.

**Comment by DDR0** [comment]
Filed a new bug for the menu offset at #372.
