### ISSUE TITLE
Compiler error: suggest braces around initialization of subobject

### ISSUE THREAD

**Issue by bentley** [anura-engine/anura#187]
These are actually only warnings but cause the build to fail (OpenBSD 6.2 -current, clang 4.0.0) due to -Werror.

    Building: src/xhtml/xhtml_node.cpp
    src/xhtml/xhtml_node.cpp:783:38: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                                            css::Specificity specificity = {9999, 9999, 9999};
                                                                            ^~~~~~~~~~~~~~~~
                                                                            {               }
    1 warning generated.
    
    Building: src/xhtml/xhtml_border_info.cpp
    src/xhtml/xhtml_border_info.cpp:315:40: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                    std::array<FixedPoint, 4> border = { dims.border_.top, dims.border_.left, dims.border_.bottom, dims.border_.right };
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                         {                                                                           }
    1 warning generated.
    
    Building: src/xhtml/xhtml_background_info.cpp
    src/xhtml/xhtml_background_info.cpp:182:42: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                            std::array<glm::vec2, 4> quadrant = { glm::vec2(-1.0f, -1.0f), glm::vec2(1.0f, -1.0f), glm::vec2(1.0f, 1.0f), glm::vec2(-1.0f, 1.0f) };
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                  {                                                                                             }
    1 warning generated.

**Comment by ghost** [comment]
Request pull with double braces?

If that doesn't get accepted, at least will point out to Makefile iteration and another pull request tweaking the Makefile.
