### ISSUE TITLE
segmentation fault from selecting typing debug console

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#205]
I somehow "selected all", cut the text, was left with nothing - not even a carat. In frustration, I typed at the keyboard a bit and got a segmentation fault after a number of keystrokes. I can't reproduce this behaviour for the life of me, but it seemed good to have some sort of record that it happened.

As follows, the console output.
```
--> set(vars.x, 5) 1
INFO: text_editor_widget.cpp:1218 : HANDLE COPY...
INFO: text_editor_widget.cpp:1251 : COPY TO CLIPBOARD: 

INFO: .թ�U
INFO: ible 

INFO: 
INFO: ns 
vars 
velocity_angle 
�U
[1]    32162 segmentation fault (core dumped)  ./anura --level=to-nenes-house.cfg --edit-and-continue
139 in  ~/anura git:(trunk) ✗  
$   
```

**Comment by DDR0** [comment]
To reproduce something similar enough: Run Anura. Type ctrl-d, ctrl-a, backspace, enter.

**Comment by davewx7** [comment]
Fixed.
