### ISSUE TITLE
Scripting error popups are occasionally several meters across.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#219]
Most screens are only a few feet across, which makes this rather hard to process. Error messages should scroll or at least be trimmed down to size when they're too large.

![image](https://user-images.githubusercontent.com/862627/35158786-15b215e0-fced-11e7-84e6-17446e85b221.png)
Pictured: About ¼ of a standard 'unknown variable' dialog box, which is in total about 13,000 pixels wide.

**Comment by davewx7** [comment]
Fixed by making anura take parameters to control maximum rows/cols used in these messages and initialized with sensible defaults:

	PREF_INT_PERSISTENT(error_message_box_max_rows, 30, "Maximum rows in error message dialog");
	PREF_INT_PERSISTENT(error_message_box_max_cols, 180, "Maximum rows in error message dialog");

**Comment by DDR0** [comment]
Confirmed fixed. Thank you.
