### ISSUE TITLE
Anura is very small by default for new mods.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#221]
Anura's window size, by default, is very small on my high-dpi monitor. This makes seeing things and using the editor somewhat difficult. Is there any reason we would not want the following options turned on by default?

```
"--auto-size-window",
"--virtual-window-width=800",
"--virtual-window-height=600",
"--virtual-window-width-max=1066",
```

Even as default they can always be overridden later by mods which require it.

**Comment by davewx7** [comment]
Turning --auto-size-window on by default.
