### ISSUE TITLE
Editor object mouseover description text runs off screen.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#222]
The editor object mouseover description text, in the object picker, sometimes runs off screen. It should soft-wrap so you can read it all.

![image](https://user-images.githubusercontent.com/862627/35173223-86e7287c-fd1f-11e7-97f1-04fea3c94dcc.png)

**Comment by ghost** [comment]
Maybe I can duck tape this after following the editor tutorial.

**Comment by ghost** [comment]
How can I reproduce, in case I passed the editor tutorial without finding?

**Comment by DDR0** [comment]
Mouse over the first object under the 'controllers' category in the editor. It should show the long tooltip.

**Comment by ghost** [comment]
Thank you. I can reproduce straight forward.

Also I located soon the code for presentation (probably not the place to apply fragmenting) at:

https://github.com/anura-engine/anura/blob/04fa38d8c0d86501bb56c26dc7c89b9bf3000701/src/character_editor_dialog.cpp#L122

I wasn't familiar with the editor (still not) and so didn't realise it was going to be written in C++. I thought it would be a case for a simple FFL level Cairo canvas `markup_text` ab/use.

I'm not familiar enough with the engine as to know which text fragmenting (https://github.com/anura-engine/anura/blob/trunk/src/cairo.cpp#L792-L1151, https://github.com/anura-engine/anura/blob/trunk/src/asserts.cpp#L52-L81, others?) apply to this, so I probably won't do. Consider this fully unassigned.

**Comment by DDR0** [comment]
I'm guessing the issue would be best solved in custom_object_type.cpp:1043, by wrapping the loaded text there. I don't know how that'll affect object serialization though - hopefully it's after that. :confused:  I'm not ye worlds best c++ programmer either, so I've created a branch at https://github.com/anura-engine/anura/compare/editor-text-wrapping to work on it. I can't get my fix to compile, basically.

**Comment by ghost** [comment]
It is a small display, so I considered appropriate to check 34955de100350bbb11cfd61d645b246e58727261 on my main device.

This is what happened, this is an uncut full screen resolution screen shot of the built in display:

<img width="1280" alt="screen shot 2018-01-28 at 10 16 15" src="https://user-images.githubusercontent.com/3533348/35480719-ae8b569a-0414-11e8-9f22-cb94f897fa76.png">

Check on [the string at github.com/frogatto/frogatto](https://github.com/frogatto/frogatto/blob/4f3ce5104de92cb96c42ed4f48332b96774b6611/data/objects/effects/misc/camera_controller.cfg#L11-L26) that ` for more.
Note: Rope preview and passepartout only works with editor unpaused.` got _actually_ cropped. On the positive side, by 34955de100350bbb11cfd61d645b246e58727261 it is a notable improvement from its base at 75b9a5f3984a35034c229eac4ac34fe49ff16212.

**Comment by DDR0** [comment]
Hm. I think I'll make the word wrap slightly larger than whatever camera_controller is manually wrapped to. That should fix the problem.

**Comment by DDR0** [comment]
![image](https://user-images.githubusercontent.com/862627/35487699-803c36b4-0433-11e8-8bd6-50bfd154c214.png)

**Comment by ghost** [comment]
https://github.com/anura-engine/anura/commit/34955de100350bbb11cfd61d645b246e58727261 was better for me than https://github.com/anura-engine/anura/commit/d0dbfab5a04189764fbf296a07e9b299eee88898, see here https://github.com/anura-engine/anura/commit/d0dbfab5a04189764fbf296a07e9b299eee88898 running on the same device:

<img width="1280" alt="screen shot 2018-01-29 at 00 31 07" src="https://user-images.githubusercontent.com/3533348/35488636-dd5e32d6-048b-11e8-92a1-b7088efcc7ba.png">

**Comment by DDR0** [comment]
<img src="https://cdn.discordapp.com/emojis/406227321872318466.png" width=20 height=20 alt=":thonk:"> I guess that's about 110 characters wide, and I've manually wrapped that description to 120 characters. Could you play around with ~/src/custom_object_type.cpp:1059 until it fits for you?
https://github.com/anura-engine/anura/blob/6477665abf548d3d7574b06a001f719296e21f85/src/custom_object_type.cpp#L1059
This'll have to do until we figure out how to relate the number of columns displayed to the window width. I've got quite a bit of room on mine, due to scaling issues. 😕  

![image](https://user-images.githubusercontent.com/862627/35488859-e6a38b54-0443-11e8-87ba-67fa244849f7.png)

**Comment by ghost** [comment]
> [...] Could you play around with ~/src/custom_object_type.cpp:1059 until it fits for you?

I found the largest number that makes the text fit in the display.

https://github.com/anura-engine/anura/blob/bdfd6e3d5402361d60ee9b1377d0bb39781edd60/src/custom_object_type.cpp#L1061-L1068

**Comment by DDR0** [comment]
Thank you. I think this issue is sufficiently fixed for now, so I'm going to mark it as closed. 🙂
