### ISSUE TITLE
Animation preview clicking to set animation frames is broken.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#226]
From (the Elisa tutorial)[https://github.com/frogatto/frogatto/wiki/Developing-Games-Using-Frogatto%27s-Engine%3A-Part-3]: "What's really nice about this interface is that I can just click [on the first frame of the walk animation, third from the top] and because it has the red rectangles in the image it automatically recognizes the walking animation."

The magic behind the rectangle recognition is broken. (In the code editor animation preview widget.) The animation never seems to get set correctly. (It detected 152 frames of animation at once on the Elisa spritesheet.) Perhaps it is because we're looking at the post-magic-colours-alpha-transform image, without the red rectangles like in the video, and we need to be looking at the pre- version?

**Comment by davewx7** [comment]
Fixed.
