### ISSUE TITLE
Pasting text over other text, in the Anura code editor, is really hard.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#227]
When I want to update my code from an external source, by copying in a new version of a block, my instinctive workflow is:

1. select text in external source and copy to clipboard
2. select text in Anura and paste from clipboard

This common workflow doesn't work because Anura automatically copies selected text to the clipboard. When the selection is made in step 2, it effectively replaces the new text with the old. This can be quite hard to detect if the changes are subtle. Using ctrl-c and ctrl-v to copy text explicitly is much more normal.

**Comment by davewx7** [comment]
Fixed.
