### ISSUE TITLE
The editor reports broken FFL too frequently when in live-reload mode.

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#231]
The editor reports broken FFL so quickly that the actual error message sometimes can't be read. When reloading a broken script in the editor, it should report the error once and then not report it again. As it stands, it spews out a few hundred thousand lines of error reporting a minute, which makes it very difficult to actually read any one of the error messages.

If the code has not changed, it should not be reloaded, and an error message should not be printed.

**Comment by davewx7** [comment]
Made it so it only reports it once.
