### ISSUE TITLE
Upgrade GLM to mint >=0.9.8.6 or >=0.9.9.0 whenever available.

### ISSUE THREAD

**Issue by ghost** [anura-engine/anura#257]
Spawns from https://github.com/anura-engine/anura/issues/255.

For the sake of _clarity_ regarding third party dependencies use, apply an upgrade at Anura as soon as there is a _valid_ replacement for GLM `0.9.8.4`.

GLM `0.9.8.5` wouldn't be _valid_ because it can't be used _cleanly_ for that purpose. Would need a (trivial) patch. That would mean no improvement in _clarity_ and probably no relevant improvement in features or whatnot.

**[There are no customizations to merge/reapply](https://github.com/anura-engine/anura/issues/255#issuecomment-379168109)**, you can do a simple replacement, [just care when adding the license](https://github.com/anura-engine/anura/issues/255#issuecomment-379168109).

Remember to use a single commit to facilitate traceability of possible later customizations.

**Comment by ghost** [comment]
[GLM 0.9.9.0 is released now](https://github.com/g-truc/glm/releases/tag/0.9.9.0).

An alpha version of it was successfully used for Anura (probably using the `citadel` stack only) by one player, but I don't remember who...

I think that player could not make it work before enabling `GLM_ENABLE_EXPERIMENTAL`.

I'll probably use it experimentally, similar to what I've been doing with ImGui 1.52, checking for issues before adding it to `trunk`.

**Comment by ghost** [comment]
I have experimented problems using the tongue attack in [Frogatto & Friends](http://frogatto.com) while using GLM 0.9.9.0 (with `GLM_ENABLE_EXPERIMENTAL`) in a clean `trunk`.

Everything being OK when running a clean `trunk` with the current GLM version.

So I think there was something wrong. 🤔

**Comment by Vultraz** [comment]
We now use `vcpkg` for libs on Windows and Mac, meaning `glm` is now using 0.9.9.8 as of this writing. We're working on moving the linux build to use package manager-provided libs too.
