### ISSUE TITLE
New engines may crash when trying to read old user data.

### ISSUE THREAD

**Issue by ghost** [anura-engine/anura#261]
This is the evil sibling of [#258: Old engines may crash when trying to read Anura 4 user data](https://github.com/anura-engine/anura/issues/258).

The evil is in that the counterpart #258 is in part a developer cooked corner case, while this other could potentially impact Frogatto customers..?

How to reproduce it more or less quickly, the macOS version:

1. Erase or move `~/Library/Application Support/frogatto/`.
2. Load https://github.com/frogatto/frogatto/tree/1.3_stable/MacOSJet on Xcode.
3. _Build and run_. If there is a compile error, fix it, [this](https://github.com/galegosimpatico/frogatto/commit/0c977aa4d6565b7f26f307435de39efa63e20563) might be of help.
4. Run a new game until a reaching toilet (a save game point), save the game, close the game.
5. Load https://github.com/anura-engine/anura/tree/master/MacOS on Xcode.
6. _Build and run_.
7. Cross the `LOAD GAME` door to reach a `CRITICAL`... unless you already effectively removed all Frogatto 1.3 saves through using the `NEW GAME` door and metal frogs (the new save points).

Can't check what happens when involving builds for Microsoft.

**Comment by DDR0** [comment]
This should be fixed now, because I renamed the frogatto module frogatto4 some time ago, so it won't try to load the old save files. :slightly_smiling_face:
