### ISSUE TITLE
Strings sum gotcha / bug.

### ISSUE THREAD

**Issue by ghost** [anura-engine/anura#278]
```
--> sum(['A', 'D'])  //   I expect 'AD'
'0AD'
--> _
```

Found while using `sum(map(range(i), '\n'))`.

**Comment by sweetkristas** [comment]
This is because the default initializer for the sum function is 0. You need
to use the form of sum, where you explicitly provide the initializer as an
empty string, i.e. sum(['A', 'D'], '')
