### ISSUE TITLE
SDL2 HAVE_M_PI definition

### ISSUE THREAD

**Issue by tono12** [anura-engine/anura#279]
Building the engine with make gives me error from multiple definitions from HAVE_M_PI.
File src/kre/SurfaceSDL.cpp gives this error. It has the definition with #ifndef, but before the include from SDL. File src/tiled/tiled.cpp algo gives the error. The definition is also before the include, in this case without the conditional definition.

For both files using #ifndef after the include solves this problem.

Edit: Im curious that no one else had this problem. Perhaps SDL library in my system should have some conditional definition that isn't there?

**Comment by ghost** [comment]
You are not the first one having this problem. From logs of the Discord server:

> <name_removed_0> - 06/29/2018
> I get an error installing the game on linux
> in making the anura engine I get
> /usr/include/SDL2/SDL_config.h:132: error: "HAVE_M_PI" redefined [-Werror]
>  \#define HAVE_M_PI 1
> src/kre/SurfaceSDL.cpp:28: note: this is the location of the previous definition
>  \# define HAVE_M_PI
> both from the AUR in arch linux, and building from soucer (cloning trunk branch and manually downloading imgui folder that doesn't get pulled by git)
> should I try to remove the Werrors flag from gcc? does anybody know?
>
> <name_removed_1> - 06/29/2018
> @<name_removed_0> maybe removing these three lines help you: [https://github.com/anura-engine/anura/blob/1c1ec65abb9900a7356cd7ef726d57412b08e561/src/kre/SurfaceSDL.cpp#L27-L29](https://github.com/anura-engine/anura/blob/1c1ec65abb9900a7356cd7ef726d57412b08e561/src/kre/SurfaceSDL.cpp#L27-L29), in any case, I dunno what will be the generic solution good for everybody.(edited)
> For some reason the compiler gets to define the symbol there before it is defined by your SDL.
> Alternatively, I guess you could make your SDL header to define that symbol only if it is not already defined (like [...] there in Anura). But maybe edit Anura better instead of SDL...
If you could report that at the issues tracker, maybe [...].
> 
> <name_removed_0> - 06/29/2018
> i'll report it later today thanks

Maybe this is a Makefile issue, if the compiler is supposed to scan all the inclusions before current project files. I don't know. At least it has a trivial workaround.

**Comment by tono12** [comment]
I'm also on arch and had the trouble with the AUR and with the sources. I also think about something from the Makefiles is causing the issue, but I can't find anything. I also suspect that something with my SDL header might be off, but not sure.

Anyway, as you said, the workaround was trivial.

**Comment by ghost** [comment]
> [...] I also suspect that something with my SDL header might be off, but not sure.
> 
> [...]

Feel free to share your SDL and GCC and Make version numbers, that could help a faster narrowing, if you have any suspect other distros could later clash at this.

**Comment by hagabaka** [comment]
I think SDL_config.h is supposed to define `HAVE_M_PI` if the system headers *have* `M_PI`, so Arch Linux's SDL_config.h does. But the bundled [external/include/SDL_config.h](https://github.com/anura-engine/anura/blob/trunk/external/include/SDL/SDL_config.h) doesn't. But I don't really think it's needed to force it to be defined here. SDL only uses this macro like this (for example [SDL_stdinc.h](https://github.com/anura-engine/anura/blob/trunk/external/include/SDL/SDL_stdinc.h), [Mac SDL_stdinc.h](https://github.com/anura-engine/anura/blob/trunk/MacOS/dylibs/SDL2.framework/Versions/A/Headers/SDL_stdinc.h)):
```
#ifndef HAVE_M_PI
#ifndef M_PI
#define M_PI    3.14159265358979323846264338327950288   /* pi */
#endif
#endif
```
Which means that even if `HAVE_M_PI` is undefined, SDL will still check if `M_PI` is already defined before defining it. So there is no need to set `HAVE_M_PI`. @sweetkristas
