### ISSUE TITLE
having 0 as the right parameter of mod() causes the game to pop into the debugger

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#280]
I.e.  `mod(4, 0)`

At the very least, we probably need to get a runtime assert on this (describing what's actually wrong with the code) so that modders don't get stumped.

**Comment by ghost** [comment]
The current plan is actually Dave's idea, and this is a **one minute** effort, so may I leave.

**Comment by DDR0** [comment]
Fixed in 2a6736f6a2c1f0fd92f750f4aa66f6057b8c1ce5. Mod 0 is now 0.
