### ISSUE TITLE
error: throw will always call terminate() [-Werror=terminate]

### ISSUE THREAD

**Issue by SnarkBoojum** [anura-engine/anura#297]
I tried compiling the repo this morning (commit d4a18a1fb17270ea449738ab5238e9a649e56d84), on my Debian unstable box, and a few files don't compile because of the above error message, because (I quote another part of the message) in C++11 destructors default to noexcept.

The problem is that the assert macro framework raises exceptions, and is used in the dtor of quite a few classes : with C++11, such dtor hence break the compilation.

There are several ways out of this:
1. never assert in a dtor! It's not logical... and that's why the default is noexcept ;
2. declare each problematic dtor as possibly raising exceptions with something like `~WronderfulClass() noexcept(false){...}`

I can provide an easy patch for the second way out.

**Comment by SnarkBoojum** [comment]
[anura_issue_297.txt](https://github.com/anura-engine/anura/files/4700630/anura_issue_297.txt)

**Comment by DDR0** [comment]
Hm, I think this is one for @davewx7 or @sweetkristas. I've poked Dave on Discord about it.

**Comment by DDR0** [comment]
Ah, looks like the patch is for `master` branch. We're using `trunk`, as noted at the bottom of [README.md](https://github.com/anura-engine/anura/blob/e877886b43175e233de8ce54c174109bd0ee3c88/README.md). Try that branch and it should be better. :+1:
