### ISSUE TITLE
Anura won't run for a clean user

### ISSUE THREAD

**Issue by SnarkBoojum** [anura-engine/anura#298]
I cloned the repositories for anura and frogatto this morning and:
1. the lack of a nice configure script didn't make easy to install build-deps (but the users won't see it once properly packaged) ;
2. there was a compilation failure (duly reported, with a patch : #297) ;
3. this allowed anura to build ;
4. after I put a symlink to the frogatto repository in anura's modules/ directory, running anura doesn't work.

The error message is:
```
Frogatto engine version 1.4
Build Options: box2d isomap save_png sdl2 shaders svg
LOADING CONFIGURATION FROM master-config.cfg
LOOKING IN 'modules/frogatto/module.cfg': 1
SET PREFERENCES PATH: ~/.frogatto/
ZZZ: FINDING BASE MODULE PATH FOR frogatto
ZZZ: CANDIDATE: modules
ZZZ: CANDIDATE VERSION [0,17]
ZZZ: CANDIDATE: /home/jpuydt/.frogatto//dlc
ZZZ: MODULE PATH FOR frogatto -> modules/frogatto/
ZZZ: FINDING BASE MODULE PATH FOR frogatto
ZZZ: CANDIDATE: modules
ZZZ: CANDIDATE VERSION [0,17]
ZZZ: CANDIDATE: /home/jpuydt/.frogatto//dlc
ZZZ: MODULE PATH FOR frogatto -> modules/frogatto/
ZZZ: FINDING BASE MODULE PATH FOR gui
ZZZ: CANDIDATE: modules
ZZZ: CANDIDATE: /home/jpuydt/.frogatto//dlc
ZZZ: MODULE PATH FOR gui -> 
PARSE ERROR: : Could not find file /home/jpuydt/.frogatto//dlc/gui/module.cfg
PARSE ERROR: : Could not find file /home/jpuydt/.frogatto//dlc/gui/module.cfg
terminate called after throwing an instance of 'json::parse_error
```

and I think the reason I see it is that my homedir is clean : probably you developers don't see it because you already have config files in there.

**Comment by DDR0** [comment]
Hm, something weird is definitely going on here. I can't get a crash either by removing my ~/.frogatto folder on Ubuntu here, nor by soft-linking the frogatto module as described.

- Does your anura-root `modules/frogatto/module.cfg` exist?
- Are you compiling Anura `trunk`, and using Frogatto `master`?

Thanks for reporting this issue. We'll have to test for it before we release.

**Comment by DDR0** [comment]
Hm, based on https://github.com/anura-engine/anura/issues/297, I'm going to close this for now, as it should be fixed in Anura Trunk. Please reopen it if the problem persists. :confused:
