### ISSUE TITLE
Can't compile trunk : imgui problems

### ISSUE THREAD

**Issue by SnarkBoojum** [anura-engine/anura#299]
In a checkout of the trunk branch, I first tried "make", but get a failure that imgui.h isn't found in src/kre/imgui_impl_sdl_gl3.cpp.

'make checkdirs' doesn't mention IMGUI.

I checked in Makefile, and there's a USE_IMGUI, on by default, but the paths don't correspond to what I have ; so I adapted them (-I/usr/include/dart/external/imgui)

After this, the compilation still failed because ImGui::Shutdown doesn't exist (private since 1.60 according to imgui_internal.h)

So I tried USE_IMGUI=no make ; alas, in Makefile, OBJ still sees src/kre/imgui_impl_sdl_gl3.cpp, and hence tries to compile it : of course it isn't found!

Finally I removed those src/kre/imgui* files, and retried USE_IMGUI=no make. But src/kre/ParticleSystemUI.cpp does something strange : it does check for USE_IMGUI before including the api... but it still uses it unconditionally!

**Comment by DDR0** [comment]
Hmm, have you ran `git submodule init`? I know that's needed on fresh
checkout. 🤔

**Comment by SnarkBoojum** [comment]
It can't compile with imgui because it uses deprecated api, and it can't compile without because src/kre/ParticleSystemUI.cpp uses the imgui api unconditionally.

**Comment by DDR0** [comment]
Yeah, imgui is pretty much a requisite now unfortunately. Could you provide
a specific error message that's preventing compilation? (Are you sure
you're using the version submodule points to?)

**Comment by SnarkBoojum** [comment]
Ah, "git submodule init" isn't the right command : "git submodule update" is what was necessary. And now it compiles ; but you should consider adding imgui as an external prerequisite and use the latest version. I'll open an issue about it, and close that one : thanks!

**Comment by DDR0** [comment]
Thank you. Glad it's working now.
