### ISSUE TITLE
Boost 1.73.0 deprecates a particular Boost.bind use.

### ISSUE THREAD

**Issue by galegosimpatico** [anura-engine/anura#308]
Excerpt from http://www.boost.org/users/history/version_1_73_0.html:

> * Changed all uses of the boost.bind placeholders to use the boost::placeholders namespace.

This makes Anura raise the following deprecation warning:

https://github.com/boostorg/bind/blob/d67c22ff44049d4769cb5bfdec03560087985bf4/include/boost/bind.hpp#L36-L41

From `external/treetree/tree.hpp` used from `src/kre/SceneGraph.hpp`.
From `src/tbs_matchmaking_server.cpp`.
From `src/tbs_bot.cpp`.
From `src/hex/hex_renderable.cpp`.
From others.

This is not a problem for now, would become a blocker at some point. I don't know if this is exactly the first version featuring the new signature replacing those deprecated.

**Comment by DDR0** [comment]
I have tried, and failed, to figure out how to fix this. By and large, we seem to use the prefixed versions.

**Comment by galegosimpatico** [comment]
Did the future hit us with this yet?

**Comment by DDR0** [comment]
No. However, I did find the flag to turn off the warning. Blissful
ignorance...
