### ISSUE TITLE
Compilation error about SDL_PIXELFORMAT_XRGB8888

### ISSUE THREAD

**Issue by MCMic** [anura-engine/anura#316]
Hello,

When attempting to build on ArchLinux, I get an error about SDL_PIXELFORMAT_XRGB8888 being redefined in src/kre/SurfaceSDL.cpp:38

I see this in the code:
```
    #ifndef _WIN32
	//This exists on Windows, and so can't be redefined.
	SDL_PIXELFORMAT_XRGB8888 =
        SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_PACKED32, SDL_PACKEDORDER_XRGB,
                               SDL_PACKEDLAYOUT_8888, 32, 4),
    #endif
```

And in /usr/include/SDL2/SDL_pixels.h I have:
```
    SDL_PIXELFORMAT_XRGB8888 =
        SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_PACKED32, SDL_PACKEDORDER_XRGB,
                               SDL_PACKEDLAYOUT_8888, 24, 4),
```

So it seems now on Linux as well this is already defined. Maybe it is possible to change to `#ifndef SDL_PIXELFORMAT_XRGB8888` ?
Also, one says 32 and says 24 for the 4th parameter, so maybe there is some compatibility problem coming.

**Comment by DDR0** [comment]
Unfortunately, `#ifndef SDL_PIXELFORMAT_XRGB8888` doesn't compile on Windows. (`redefiniton; previous definition was 'enumerator'`.) I don't know of any #ifdef variables which get defined for only Arch Linux, and as I don't have an Arch install here I can't really test this very easily.

**Comment by DDR0** [comment]
Thanks for reporting this, I think this isn't the first time this has caused problems.

**Comment by DDR0** [comment]
Changed hack to be only on macs, since that's possibly the last holdout requiring it. https://github.com/anura-engine/anura/commit/9de855e828c891fa0d2ac9da5301b02d1ea3eed2

@MCMic, this should fix it on Arch, let me know if it doesn't.

**Comment by MCMic** [comment]
It does fix the compilation. The game I wanted to test (argentum) does not work but I have no idea if this comes from anura or argentum.

**Comment by DDR0** [comment]
Oh shoot. Try uh grabbing a copy of Anura from just after the last commit
to Argentum Age and applying the change I made to fix the issue here.

Maybe swing by the Discord (link on wiki) and we can help in person. 🙂
