### ISSUE TITLE
Compilation error about PIXELFORMAT_XRGB8888 [Ubuntu]

### ISSUE THREAD

**Issue by GSchuemann** [anura-engine/anura#317]
Hi,

as you might remember I am the one maintaining the Argentum Age snap. Today I wanted to make some changes to it, but I got this error when compiling anura:
```
Building: src/kre/SurfaceSDL.cpp
src/kre/SurfaceSDL.cpp: In function ‘Uint32 KRE::{anonymous}::get_sdl_pixel_format(KRE::PixelFormat::PF)’:
src/kre/SurfaceSDL.cpp:86:60: error: ‘SDL_PIXELFORMAT_XRGB8888’ was not declared in this scope
     case PixelFormat::PF::PIXELFORMAT_XRGB8888:     return SDL_PIXELFORMAT_XRGB8888;
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
src/kre/SurfaceSDL.cpp:86:60: note: suggested alternative: ‘SDL_PIXELFORMAT_ARGB8888’
     case PixelFormat::PF::PIXELFORMAT_XRGB8888:     return SDL_PIXELFORMAT_XRGB8888;
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
                                                            SDL_PIXELFORMAT_ARGB8888
Makefile:235: recipe for target 'build/kre/SurfaceSDL.o' failed
make: *** [build/kre/SurfaceSDL.o] Error 1
make: *** Waiting for unfinished jobs...
```
Since I saw that you had this issue recently here, I tried reverting to 9de855e, but that didn't help. So I have gone back to the last commit that I know was working 0de6ecf and the compilation worked with that. So this is a regression introduced in the last year. 

PS: If you want a CI-System for Linux compilation testing I could create one, since I've most of the work done in the snap for CI anyway (it isn't on github yet, but I will update my yaml to work with launchpads CI in the near future).

EDIT: I had the idea trying the commit before 9de855e, 33da1fe. With that I didn't run into the issue, compilation stops at a later point, but that would be a different issue. So fixing it for Arch and making it Mac only, breaks it on Ubuntu. At least it breaks in a Ubuntu 18.04 Multipass VM.

**Comment by rkettering** [comment]
Btw, feel free to join the frogatto discord:   https://discord.gg/Uws7GYw

DDR mentions there:
> I think the solution is to git cherry-pick my fix.

Any work towards CI would be awesome - would be great to get any heads-up about Anura breakage since we're trying to get a release of Frogatto out here, sometime this year.

**Comment by DDR0** [comment]
I made a new branch, [argentum-age](https://github.com/anura-engine/anura/tree/argentum-age), which lacks the necessary commits for [Argentum Age](https://github.com/davewx7/citadel/) to run but contains the necessary commits for it to compile on my machine now. Ideally, we would bisect the engine and find out when it stopped loading whatever is breaking it, but this will do for now. Both projects have been quite quiet recently.
