### ISSUE TITLE
src/sound.cpp:1232:40: error: expected primary-expression before ‘int’

### ISSUE THREAD

**Issue by isopix** [anura-engine/anura#321]
Building: src/sound.cpp
src/sound.cpp: In member function ‘virtual void sound::{anonymous}::BinauralDelaySoundEffectFilter::MixData(float*, int)’:
src/sound.cpp:1232:40: error: expected primary-expression before ‘int’
 1232 |             const int nsamples_delay = int(std::abs<float>(delay_)*SampleRate);

Built using:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=anura-git

**Comment by Vultraz** [comment]
I already have this fix on the `buildsystem-upgrade` branch (627d08fb5254b5c66d315f1706089905c2704059).
