### ISSUE TITLE
block_destroy_helper

### ISSUE THREAD

**Issue by avinashamanjha251** [anura-engine/anura#384]
Hi Dev Team,

While working on the face scan SDK, I have encountered the same crash several times. However, it only shows "block_destroy_helper." Please assist me in resolving this issue. Added crash log file.

Thank you.

[stacktrace.txt](https://github.com/anura-engine/anura/files/14533411/stacktrace.txt)

**Comment by DDR0** [comment]
I don't understand what this has to do with Anura.

**Comment by avinashamanjha251** [comment]
@DDR0 I'm experiencing crashes from the SDK.
