### ISSUE TITLE
More error when I compile release version on mac

### ISSUE THREAD

**Issue by Angluca** [anura-engine/anura#49]
More more error on xcode6 and use master branch, I changed more file, I can't fix them, But debug version hasn't error.

some error.
# include <GL/gl.h> => <OpenGL/gl.h>

and Graghics::color must include head file.

Don't know how fix it, I have no study boost.
anura/MacOS/boost/smart_ptr/intrusive_ptr.hpp:91:23: No matching function for call to 'intrusive_ptr_add_ref'

**Comment by sweetkristas** [comment]
master branch is deprecated for building from at the moment. Please switch to trunk. git checkout trunk

**Comment by Angluca** [comment]
Use trunk branch open frogatto module on mac.
Game crash when I open develop gui after a few times, And more chaos pixel on screen.
