### ISSUE TITLE
Objects' rendered-rectangle size is often cut off at an odd number of pixels.

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#70]
I'm guessing this is probably an off-by-one error, but at the moment, quite a few objects, on their far edges, are cut off half a pixel too soon.  This is most visible on objects that are meant to be used in a tile-like manner, and stacked end-to-end.

![cropped-blitting](https://cloud.githubusercontent.com/assets/863312/7720725/45011790-fe96-11e4-9c6d-ca3114a5099b.png)

**Comment by sweetkristas** [comment]
What level is this on? Yes I realize it applies to more than one of them. Just to give me an easy test case to compare to.

**Comment by rkettering** [comment]
`--level celadon-clearing.cfg`  This should be visible to the left of the initial starting point (if it hasn't changed since last I encountered it).

**Comment by rkettering** [comment]
As far as I can tell, this seems to be fixed, now.
