### ISSUE TITLE
Water is displaying incorrectly.

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#73]
Sometimes it's invisible, sometimes its the wrong color.  In neither case is it drawing the solid line on the top.

For what it's worth, I actually would have no problems with switching to a system where displaying this is not done by a special engine feature, but is instead done by drawing primitives via FFL.  I have a number of things I'd like to improve about the display of water (including adding some entirely new kinds of liquid), and the current baked-in engine feature doesn't give me the flexibility I need to do them.

`--level celadon-clearing.cfg` (down and to the left from the starting position)
![image](https://cloud.githubusercontent.com/assets/863312/7743213/35d73966-ff5e-11e4-894b-af5bfc22d05a.png)

`--level to-nenes-house.cfg` (down and to the right from the starting position)
![image](https://cloud.githubusercontent.com/assets/863312/7743265/b55f9f52-ff5e-11e4-981a-9dd49a2d2ceb.png)

**Comment by rkettering** [comment]
It's worth noting I'm seeing the improvements from 35da8feb92e0 correctly; most water is red, but it seems to usually be visible.  (acid in the dungeons ends up purple rather than green, though it ends up red in the caves (plagued-mine)).

I am noticing all water is only showing one of the two triangles composing the water rect.  I expect this is a known issue, but it's worth mentioning in the off-chance it's not.  :neutral_face:

Here are some examples of acid:
`dungeon-entrance.cfg`, to the right of the start position
`killer-bunnies.cfg` to the right

Acid in a cave:
`plagued-mine.cfg` to the right

Water:
`tempo-docks.cfg`
`splash-hop.cfg`

**Comment by sweetkristas** [comment]
The change was only temporary, to get something on-screen at least.

**Comment by DDR0** [comment]
This should be fixed now.
