### ISSUE TITLE
Compound objects have positioning errors on their spawned parts:

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#76]
Both examples here are one pixel (2 with our normal zoom factor) to the left of their intended position.

`crevice-village-house-3-backroom.cfg`
![image](https://cloud.githubusercontent.com/assets/863312/7743630/3ab811fe-ff62-11e4-88fc-53948dd369f1.png)

`crevice-village-house-3.cfg`
![image](https://cloud.githubusercontent.com/assets/863312/7743643/5df8a17e-ff62-11e4-826d-0d931a432efa.png)

**Comment by sweetkristas** [comment]
duplicate of #70

**Comment by rkettering** [comment]
Yeah, looks like fixing #70 fixed this.
