### ISSUE TITLE
Fullscreen only blits to the upper-left quarter of the screen (and isn't zoomed in)

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#86]
The fullscreen mode does transition in correctly, and the rest of the screen blacks out; it's just that the whole of the final fullscreen window isn't being used for the game.

Running on a mac with OS 10.10.3

**Comment by sweetkristas** [comment]
Applies to all OS's.

**Comment by casesensitive** [comment]
I have a similar issue, when i try to go fullscreen or maximize the window, nothing happens, I'm running it under Debian

**Comment by rkettering** [comment]
Fixed in several commits:
219d23e56a62c70d9f53f501e38d611b2132c8df
fbf2bd5e285941e883ec4e3ad6b5e32fbac46610
ea3479dac52934e749013b16f7f199d54732ec01
97a72fa0b8ba49f55185f7774a552057a34942c8
10f62eecfb129694bc211f1f9bd3315d65ec7a65

(amongst others)
