### ISSUE TITLE
Editor click targets seem to be about 16 pixels (a tile's height) higher than expected.

### ISSUE THREAD

**Issue by rkettering** [anura-engine/anura#88]
This applies to either placing tiles, or objects - to select an object, I have to place the mouse cursor about a tile above where it visibly displays.  To place a tile, I have to place the mouse cursor about a tile higher than intended.

You may have to use the arrow keys to scroll the level around to initiate this behavior, and/or pause the editor.  Not sure.

**Comment by Phanterm** [comment]
This problem compounds itself as one zooms in and out, making editing from anything other than 100% zoom very difficult.

**Comment by Autofire** [comment]
When editing on Linux, the issue is far more noticeable. Also, oddly it seems like the issue is more pronounced as the mouse approaches the bottom of the screen. (I think it could be tied to the fact that the game's display seems to 'stretch' all the non-editor things downward.)

**Comment by rkettering** [comment]
Temporarily has been ameliorated by 2090d14897bc00ace2d524b2a0bbb1f860fb2a09 , but comments on the issue suggest this fix may be internally less than ideal.  (From a usage perspective, however, it's completely fixed. :) )

**Comment by rkettering** [comment]
Closed for the time being.
